### ISSUE TITLE
Stuck make install

### ISSUE THREAD

**Issue by abelardolg** [mtarld/apip-ddd#45] opened 2023-07-09 10:41 UTC
Hi there!
Cloned this repo, I run make install but...
![image](https://github.com/mtarld/apip-ddd/assets/22522883/e1aeba3b-ba0a-4f97-a213-2540aa60acff)

What's wrong?
I cloned this repo today.

**Comment by mtarld** [comment] 2023-12-27 11:04
Hi @abelardolg, sorry for the late reply.

I cannot reproduce the issue, does it still happen for you?

**Comment by mtarld** [comment] 2023-12-29 09:46
I'm going to close the issue, if you are still struggling with it, feel free to reopen it!

**Closed by mtarld** 2023-12-29 09:46 UTC
